# @name create-user
POST http://localhost:3000/user
Content-Type: application/json

{
    "name": "Maria Doe",
    "email": "mariadoe@test.com",
    "password": "123"
}

###

# @name get-users
GET http://localhost:3000/users

###

# @name get-user-by-id
GET http://localhost:3000/user/1

###

# @name delete-user
DELETE http://localhost:3000/user/1